baseurl = "http://key-amb.github.io/bootie-docs-demo"
languageCode = "en-us"
title = "Bootie Docs"
theme = "bootie-docs"

[params]
  description = "A simple Hugo theme for documentation."
  withSitePosts = true
  mainMenu = ["quickstart"]